### ISSUE TITLE
system/script/args is a block if called from the command line

### ISSUE THREAD

**Issue by Dobeash** [Oldes/Rebol-issues#2519]
Create a simple script as follows:
```
Rebol []
print type? system/script/args
```
then from the command prompt enter `rebol3-base-windows-x64.exe "script.r" "1"`.

system/script/args is a `block!` instead of the expected `string!`. It is a `string!` if called from another script with `do/args`.

**Comment by Oldes** [comment]
But when you use `do/args the-script ["a" 1]`, you will get `block!`.

**Comment by Oldes** [comment]
That system boot is also using these arguments, not just the script and so are being [parsed in the native part](https://github.com/Oldes/Rebol3/blob/master/src/os/host-args.c).

When building a custom Rebol based app, one may use `RAW_MAIN_ARGS` define, so the arguments would be [converted to block of strings](https://github.com/Oldes/Rebol3/blob/00f44fa2b3a99f0c8987371a09f6a664a01091e9/src/os/host-args.c#L207) and leaved on interpreter to process it. That is what I do in the Siskin Builder utility [here](https://github.com/Siskin-framework/Builder/blob/f48c28f0a2ef5d15df188693cfffeee99b319011/tree/rebol/siskin.nest#L35-L37) and [there](https://github.com/Siskin-framework/Builder/blob/f48c28f0a2ef5d15df188693cfffeee99b319011/tree/rebol/Siskin/siskin.reb#L202-L266).

But if you have an idea, how to improve it, let me know. But remember, that it is more complex than it may look on first sight.

**Comment by Oldes** [comment]
Btw.. there are some related tests: https://github.com/Oldes/Rebol3/blob/master/src/tests/units/call-test.r3

The reason, why you cannot have just a string in `system/script/args` is, that you get an array of strings initially and when it would be joined into one string, there would be an information lost.

I recommend you to follow [related issues in this repository](https://github.com/Oldes/Rebol-issues/issues?q=system%2Fscript%2Fargs) and read the comments:)

**Comment by Oldes** [comment]
@Dobeash btw... what you would like to get in the `system/script/args`, when you would use in the command line:
```
rebol3 script.r 1 "a b" %c
```
?

**Comment by Oldes** [comment]
Some of related issues: https://github.com/Oldes/Rebol-issues/issues/1890, https://github.com/Oldes/Rebol-issues/issues/2140, https://github.com/Oldes/Rebol-issues/issues/2227, https://github.com/Oldes/Rebol-issues/issues/2228, https://github.com/Oldes/Rebol-issues/issues/2469

**Comment by Oldes** [comment]
You should probably understand, that `do/args` is not using a new interpreter instance and so you can have in these args normal Rebol values... but when you use system call, you receive just an array of null-terminated strings.

If you would like to compare, than you should compare with `launch/args` instead, which starts a new process. But I don't think `launch` is correct enough, when you don't use just a plain and well formatted string for its `args`. Although it was marked as fixed in the CureCode https://github.com/Oldes/Rebol-issues/issues/628 - tests for it would be welcomed.

**Comment by Dobeash** [comment]
Ah, my bad on the issue reporting ... didn't realise issues under **3.10.0** was different to the dedicated issue repository link (first time using GitHub).

> `do/args` is not using a new interpreter instance and so you can have in these args normal Rebol values

Wow, I never knew that. I'd always just passed a single string and used split in the called script.

> when you use system call, you receive just an array of null-terminated strings

This is also something I wasn't aware of, so explains the "inconsistency" I was seeing. My use case is that I have scripts that have different entry points so a script expecting a string argument now needs to do:

```
arg: either block system/script/args [first system/script/args] [system/script/args]
```
This reminds me of the old `load` behaviour debate:

```
>> load "1 2"
== [1 2]
>> load "1"
== 1
```
I'd be tempted to apply the same logic for system call (i.e. only return a bock if more than one value is provided).

**Comment by Oldes** [comment]
Preferably you should use `transcode` for that:
```rebol
>> transcode "1"
== [1]
>> transcode "1 2"
== [1 2]
```
`load` is too high level for this task:
```
>> profile [[load "1"] [transcode "1"]]

Running 2 code blocks 10 times.
-------------------------------------------------------------------------------
Time               | Evals  | S.made | S.expa | Memory      | Code
1.0x (800ns)       | 1      | 1      | 0      | 64          | [transcode "1"]
18.38x (15μs)      | 142    | 3      | 0      | 200         | [load "1"]
-------------------------------------------------------------------------------
```
