### ISSUE TITLE
find/any returns incorrect result

### ISSUE THREAD

**Issue by Dobeash** [Oldes/Rebol-issues#2522]
Works as expected:
```
>> find/any %Scripts/abcd %*abc
== %Scripts/abcd
```
Returns incorrect result:
```
>> find/any %Scripts/ibcd %*ibc
== %pts/ibcd
```

**Comment by Oldes** [comment]
@Dobeash I have a fix (hopefully), but right now I don't have much time to write all the test cases. And it really would be good to test not just this case, but all other possible wild card variants to see, if the fix does not break something else... do you want to help me with it? To be honest... writing the tests is often much more time consuming than actually fixing some code.

**Comment by Oldes** [comment]
As there already were [some tests](https://github.com/Oldes/Rebol3/blob/34df085081f4e162ccea2f0d6feed12c9ab2afe3/src/tests/units/series-test.r3#L76-L135) and all are still correct, I decided to push the fix.. more tests are still wanted... there is so many combinations:/

**Comment by Dobeash** [comment]
Found another breaking case. Works as expected:

```
>> find/any %A.csv %A*.csv
== %A.csv
```

Returns incorrect result:

```
>> find/any %A..csv %A*.csv
== none
```

Not sure whether you wanted to reopen this issue or create a new one.

**Comment by Oldes** [comment]
Yeh... it seems to be an issue in this case.
