### ISSUE TITLE
Binary to string conversion memory leaks

### ISSUE THREAD

**Issue by Dobeash** [Oldes/Rebol-issues#2523]
Start a fresh console and `do` the following:
```
Rebol []

bin: make binary! mb: 1024 * 1024

loop mb / 8 [append bin "Rebol310"]

recycle

start: stats

repeat i 16 [
    kb: i * 64
    copy/part bin kb * 1024
    prin format [-4 " Kb -> "] kb
    recycle
    print [to integer! stats - start / 1024 "Kb used"]
]

recycle

print ["^/End:" to integer! stats - start / 1024 "Kb used"]
```
It will end with stats almost unchanged. Now add `to string!` prior to the `copy/part` and try the same thing again. This time stats will show an extra 4Mb in use.

Same issue occurs when using `read/string`, and is also present in every other Rebol variant I've tried. The "sweet" spot seems to be 256Kb, so for large file reads I use the following:
```
read-string: function [
    source [file!]
] [
    either 262144 >= len: size? source [read/string source] [
        s: make string! len
        p: open/read source
        while [not tail? p] [
            append s to string! copy/part p 262144
        ]
        close p
        deline s
    ]
]
```
but the issue with this approach is potentially splitting on a multibyte character.

**Comment by Oldes** [comment]
There is no memory leak. You are just experiencing, how Rebol deals with memory.
It allocates series from a memory pools, which are of special sizes.. you can see them using `show/stats`

Having your large binary, you can see how much memory is used using `profile`:
For example if you copy one byte, you make a series with space for 8 bytes (including the terminating byte):
```
>> profile [[copy/part bin 1]]         

Running 1 code blocks 10 times.
----------------------------------------------------------------------------------
Time               | Evals  | S.made | S.expa | Memory      | Code
1.0x (2μs)         | 2      | 1      | 0      | 8           | [copy/part bin 1]
----------------------------------------------------------------------------------
```
When you prepend `to string!`, than you are making 2 series! One for the binary part and the second for the string:
```
>> profile [[to string! copy/part bin 1]]

Running 1 code blocks 10 times.
--------------------------------------------------------------------------------------------
Time               | Evals  | S.made | S.expa | Memory      | Code
1.0x (3μs)         | 4      | 2      | 0      | 16          | [to string! copy/part bin 1]
--------------------------------------------------------------------------------------------
```
Also in your code you expect that `recycle` frees everything in one pass, which is not true... so far GC works in 2 passes... one marks unused series and on the second it frees them... so you should call `recycle` 2x to get correct data.

**Comment by Oldes** [comment]
Btw... here is related improvement wish: https://github.com/Oldes/Rebol-issues/issues/2480

Also... you are right... your `read-string` is very unsafe! The binary is supposed to be UTF-8, when you convert to string and so you may easily split in in the middle of an unicode char and so corrupt your input data.

**Comment by Oldes** [comment]
It can be also noted, that the binary to string conversion is using shared unicode buffer `BUF_UTF8`:
https://github.com/Oldes/Rebol3/blob/master/src/core/s-unicode.c#L659

(it expands when needed, but so far never shrinks)
