### ISSUE TITLE
to-date to-integer 3-Jun-2023 returns 7-May-2003/13:09:16

### ISSUE THREAD

**Issue by fvanzeveren** [Oldes/Rebol-issues#2550]
Hello
I want to convert date! to integer! for efficient storage into an SQLite Database...
I was therefore expecting that 
`to-date to-integer 3-Jun-2023` would return `3-June-2023`, but it returns `7-May-2003/13:09:16` instead :/.
I tried it on Windows 11, Haiku OS and Debian. Same issue!
Maybe I am doing sth wrong, but this behaviour looks weird to me.

Thank you.

François

**Comment by Oldes** [comment]
It is a bug... the reason is, that the time part is missing. Compare:
```rebol
>> to date! to integer! 3-Jun-2023/0:00
== 3-Jun-2023/0:00

>> to date! to integer! 3-Jun-2023      
== 7-May-2003/13:09:16 ;== this should be also 3-Jun-2023/0:00
```

**Comment by Oldes** [comment]
Fixed... but there is no way to get just `3-Jun-2023` as you maybe expect, because the integer value is _unixtime_ (number of seconds since 1-Jan-1970). It was not designed to keep just a date.

**Comment by Oldes** [comment]
Btw... it is also good to note, that in Rebol, `to-date`, `to-integer` and so on are just a helpful functions... If you want to optimise your code, use `to date!`, `to integer!` so you will same a function evaluation.

In case of `to-date`, the code is even more complicated, as it tries to decode multiple formats... like:
```rebol
>> to-date probe to-idate now
"Fri, 9 Jun 2023 17:08:40 +0200"
== 9-Jun-2023/17:08:40+2:00
```

See: https://github.com/Oldes/Rebol3/blob/b18dc57d/src/mezz/mezz-date.reb#L52-L79

**Comment by fvanzeveren** [comment]
Thank you for the tip!

Cheers

**Comment by Oldes** [comment]
Btw.. now https://github.com/Oldes/Rebol-issues/issues/2551 it is also possible to convert date to decimal (having a Julian date as a result).
```rebol
>> to date! 2400000.0
== 16-Nov-1858/12:00

>> date: to date! 2400000.0
== 16-Nov-1858/12:00

>> to decimal! date         
== 2400000.0

>> date/julian
== 2400000.0

>> to date! date/julian     
== 16-Nov-1858/12:00
```
