### ISSUE TITLE
RISC-V Support

### ISSUE THREAD

**Issue by acook** [Oldes/Rebol-issues#2584]
Although the number is still small, I'm seeing more and more RISC-V devices out there. At some point it might be nice to ensure that Rebol can target this growing platform. 

This would also require a Siskin build for that target architecture.

**Comment by Oldes** [comment]
It should not be such a problem, but RISC-V emulator would be needed, so I could make automatic builds in cloud like I do for [HaikuOS](https://github.com/Oldes/Rebol-Docker/tree/master/haiku).. do you have experience with any?
Maybe this one https://github.com/DavidBurela/riscv-emulator-docker-image ?

**Comment by Oldes** [comment]
I just ordered VisionFive V2 Quad-core RISC-V dev board to play with it :-) Estimated delivery date is end of February. But I don't have much time at this moment anyway.

**Comment by acook** [comment]
That image uses QEMU and QEMU is the standard emulator, so that seems like the most reasonable starting point.

- https://wiki.qemu.org/Documentation/Platforms/RISCV

It is using [dqib](https://gitlab.com/giomasce/dqib) to build and install a Debian image into QEMU, so it's pretty neat that it can get a RISCV Linux install ready in so few steps. 

---

I also found these, just in case:

- https://github.com/LekKit/rvvm
- https://github.com/d0iasm/rvemu
- https://github.com/fwsGonzo/libriscv

**Comment by Oldes** [comment]
@acook Initial RISC-V build can be downloaded from here:
https://rebol.tech/builds/3.15.1/rebol3-bulk-linux-riscv64.gz

![image](https://github.com/Oldes/Rebol-issues/assets/454805/d3b9d375-c6a7-46a1-9e94-a6384066b36e)

**Comment by Oldes** [comment]
Cross-compilation: https://github.com/Siskin-framework/Builder/commit/8713961709d2c3857799ab7eff625f898d4049d3

**Comment by acook** [comment]
I expected this to be aspirational, not something with a turnaround of a week. Really goes to show how platform support has matured. Both GCC and QEMU and Linux, all handling it smoothly. I don't even see any RISC-V specific changes outside of the build tools. 

![Screenshot from 2024-01-30 13-00-40](https://github.com/Oldes/Rebol-issues/assets/71984/a2b49647-4b05-4cb9-b617-ba5c87278709)
