### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by ldci** [Oldes/Rebol-issues#2610]
Some modules such as blend2D do not work with Rebol3-3.18.0 version.

**Comment by ldci** [comment]
OK problem corrected with your version 👍

**Comment by ldci** [comment]
No problem when using your https://github.com/Oldes/Rebol3/releases/download/3.18.0/rebol3-bulk-macos-arm64.gz. Don't work when I'm using sources and siskin .

**Comment by ldci** [comment]
Problem solved : macOS codesign. I've to desactivate `export SISKIN_SIGN_IDENTITY=DEF212C364479537542FEB630620CDE0C7CECAD3`in my .profile when compiling your sources with siskin

**Comment by Oldes** [comment]
The issue probably is, that all my builds are signed with my (personal) developer's identity, which your system don't know and so probably don't trust.. or application signed with my identity don't trust an extension, which you build yourself and is signed with yours (if you have `SISKIN_SIGN_IDENTITY` defined).

Possible solution is to _resign_ my binaries you use with your identity with command like:
```
/usr/bin/codesign --force -s $MACOS_IDENTITY_ID ./tree/rebol/Rebol/build/rebol3-base-macos-x64 -v
```
Where `MACOS_IDENTITY_ID ` would be your identity which is probably `DEF212C364479537542FEB630620CDE0C7CECAD3`
So in your case the command would be:
```
/usr/bin/codesign --force -s DEF212C364479537542FEB630620CDE0C7CECAD3 ./tree/rebol/Rebol/build/rebol3-base-macos-x64 -v
```

**Comment by Oldes** [comment]
Just for a record, one can use this command to find personal signing identities:
```
security find-identity -v -p codesigning
```
