### ISSUE TITLE
Error During Bulk Compilation (3.18.0)

### ISSUE THREAD

**Issue by acook** [Oldes/Rebol-issues#2611]
Building from commit 4b1085df08ed21bf847e2cf4169a89007c79ab07 fails with errors due to missing defines. This surprised me because I have been building successfully with this same setup. I updated Siskin in case there was an incompatible change, but the errors persist.

```
6:    Rebol/Bulk linux-x64
```

```
Linking binary:

 [SISKIN] EVAL: /usr/bin/gcc -o /home/user/Source/Clones/Rebol3/build/rebol3-bulk-linux-x64 @make/tmp/gcc-x64/rebol3-bulk-linux-x64/objects.txt -O2 -fPIC -m64    -DREBOL_OPTIONS_FILE=\"gen-config.h\" -D__LP64__ -D_FILE_OFFSET_BITS=64 -DENDIAN_LITTLE -DMBEDTLS_AES_C -DMBEDTLS_ASN1_PARSE_C -DMBEDTLS_ASN1_WRITE_C -DMBEDTLS_BIGNUM_C -DMBEDTLS_CTR_DRBG_C -DMBEDTLS_DHM_C -DMBEDTLS_ECDH_C -DMBEDTLS_ECDSA_C -DMBEDTLS_ECP_C -DMBEDTLS_ENTROPY_C -DMBEDTLS_OID_C -DMBEDTLS_PKCS1_V15 -DREB_EXE -DTEST_EXTENSIONS -DTO_LINUX -DUNICODE -ldl -lm  -L/home/user/Source/Clones/Rebol3/build/
/usr/bin/ld: make/tmp/gcc-x64/rebol3-bulk-linux-x64/home/user/Source/Clones/Rebol3/src/core/m-gc.c.o: in function `Queue_Mark_Series':
m-gc.c:(.text+0xc): undefined reference to `GC_Mark_Queue'
/usr/bin/ld: make/tmp/gcc-x64/rebol3-bulk-linux-x64/home/user/Source/Clones/Rebol3/src/core/m-gc.c.o: in function `Recycle':
m-gc.c:(.text+0x933): undefined reference to `GC_Mark_Queue'
/usr/bin/ld: make/tmp/gcc-x64/rebol3-bulk-linux-x64/home/user/Source/Clones/Rebol3/src/core/m-gc.c.o: in function `Init_Memory':
m-gc.c:(.text+0xcec): undefined reference to `GC_Mark_Queue'
/usr/bin/ld: make/tmp/gcc-x64/rebol3-bulk-linux-x64/home/user/Source/Clones/Rebol3/src/core/n-system.c.o: in function `N_stats':
n-system.c:(.text+0x368): undefined reference to `Eval_Collisions'
/usr/bin/ld: make/tmp/gcc-x64/rebol3-bulk-linux-x64/home/user/Source/Clones/Rebol3/src/core/t-map.c.o: in function `Find_Key':
t-map.c:(.text+0x102): undefined reference to `Eval_Collisions'
/usr/bin/ld: t-map.c:(.text+0x173): undefined reference to `Eval_Collisions'
/usr/bin/ld: t-map.c:(.text+0x233): undefined reference to `Eval_Collisions'
collect2: error: ld returned 1 exit status

           .-.
          /'v'\
         (/uOu\)
═[SISKIN]══"═"═>  Build failed (1)
```

---

I have a build dated `14-Dec-2023` `REBOL/Bulk 3.15.1 (Oldes branch)`, so I know building bulk worked previously. 

If I'm looking at the code right, `Eval_Collisions` and `GC_Mark_Queue` are defined in `sys-globals.h` which is included in `sys-core.h` which is then included everywhere else.

On [line 119](https://github.com/Oldes/Rebol3/blob/master/src/include/sys-globals.h#L119-L121) of `sys-globals.h` the variable `Eval_Collisions` is defined conditionally:

```c
#ifdef DEBUG_HASH_COLLISIONS
TVAR REBI64 Eval_Collisions; // Hash collisions
#endif
```

If that conditional fails that might cause a problem. 

On the other hand, `GC_Mark_Queue` is not defined conditionally, and `sys-core.h` is included in `m-gc.c` so I am not sure why it is not being found?

**Building Core succeeds.**

**Comment by Oldes** [comment]
I don't see any issues when building for all platforms... https://github.com/Siskin-framework/Builder/actions/runs/10021732928
Maybe you have some conflict with your local content... can you try to make a clean build?

I don't know how exactly you compile... you can see all steps I use to make the release builds in this file:
https://github.com/Siskin-framework/Builder/blob/master/.github/workflows/rebol.yml

**Comment by Oldes** [comment]
My guess is, that you maybe don't have the latest sources... 
When working with the builder which already downloaded some sources, you may consider to use `--clean` and `--update` options!
![image](https://github.com/user-attachments/assets/df174c38-1426-46b2-b332-a21b4a323710)

**Comment by Oldes** [comment]
`--clean` options removes already compiled object files
`--update` calls `git pull` in all linked repositories

**Comment by Oldes** [comment]
`DEBUG_HASH_COLLISIONS` define is there to debug, how many hash collisions there is, when running some code.. I used it to compare various hash strategies. You should not have it enabled by default.

**Comment by Oldes** [comment]
When using the interactive version, use just `clean` and `update` (or `c` and `u`)

**Comment by Oldes** [comment]
The `clean` option must be used with the target you want to build (number or name).

**Comment by Oldes** [comment]
If you already did some build and just _pull_ new content from git, only modified files are downloaded, and so when you do another build, you most probably will see something like this:
![image](https://github.com/user-attachments/assets/edbee0ae-362b-48e4-8e02-f06d4eea21bf)
You can see, that only some files are being compiled... but old one may require some important changes and the linker fails. 
So you should always use the `clean` option` when some big update happens.

**Comment by Oldes** [comment]
The `clean` option with the `rebol3-bulk-linux-x64` target would remove complete content of the `make/tmp/gcc-x64/rebol3-bulk-linux-x64/` directory and so all files would be compiled again.

**Comment by acook** [comment]
I was doing `clean` and `update` from interactive mode, but it did not seem to be doing anything. I didn't realize it required a build target as well. Running:

```sh
siskin ./make/rebol3.nest --clean --update rebol3-bulk-linux-x6
```

Builds successfully.

Thanks!
